name: Build and Release ChatGPTWhisperer Plugin

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    env:
      GHIDRA_VERSION: 11.2
      GHIDRA_INSTALL_DIR: ${{ github.workspace }}/ghidra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Ghidra 11.2
        run: |
          wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_11.3.1_build/ghidra_11.3.1_PUBLIC_20250219.zip
          unzip ghidra_11.3.1_PUBLIC_20250219.zip -d ghidra

      - name: Build ChatGPTWhisperer Plugin
        run: ./gradlew buildExtension

      - name: Create GitHub Release and Upload Plugin ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

